{{- if .Values.namespaces.enabled -}}
{{- range $namespace := .Values.namespaces.list }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .name }}
{{ if $namespace.options -}}
{{ toYaml $namespace.options | indent 2 }}
{{ end }}
{{- end }}
{{- end -}}