# Default values for secrets.

# Use for mapping SSL data to k8s secrets. Certs/key data must be encoded in base64 format.
# Example:
# ssl_certificate:
#   enabled: true
#   domains:
#   - name: foo.com
#     private_key: Zm9vLmNvbQo=
#     certificate: Zm9vLmNvbQo=
#   - name: bar.com
#     private_key: YmFyLmNvbQo=
#     certificate: YmFyLmNvbQo=
ssl_certificate:
  enabled: false

# Use for creating Docker Registry secrets.
# Example:
# docker_hub_secrets:
#   enabled: true
#   logins:
#   - name: docker
#     dockerconfigjson: ZG9ja2VyY29uZmlnanNvbgo=
docker_hub_secrets:
  enabled: false

# Use for creating usual k8s secrets.
# Example:
# custom:
#   enabled: true
#   secrets:
#   - name: mysecret
#     type: kubernetes.io/basic-auth
#     data:
#       login: bXlzZWNyZXQK

custom:
  enabled: false
