{{- if .Values.webserver.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rails.name" . }}-webserver
  labels:
    app: {{ include "rails.name" . }}-webserver
    app.kubernetes.io/name: {{ include "rails.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ include "rails.version" . }}
    environment: {{ include "rails.environment" . }}
    product: {{ .Values.product }}
    helm.sh/chart: {{ include "rails.chart" . }}
spec:
  replicas: {{ .Values.webserver.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "rails.name" . }}-webserver
      app.kubernetes.io/name: {{ include "rails.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      environment: {{ include "rails.environment" . }}
      product: {{ .Values.product }}
  minReadySeconds: {{ .Values.replica.minReadySeconds }}
  progressDeadlineSeconds: {{ .Values.replica.progressDeadlineSeconds }}
  revisionHistoryLimit: {{ .Values.replica.revisionHistoryLimit }}
  strategy:
    type: {{ .Values.replica.strategy }}
  template:
    metadata:
      labels:
        app: {{ include "rails.name" . }}-webserver
        app.kubernetes.io/name: {{ include "rails.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/version: {{ include "rails.version" . }}
        environment: {{ include "rails.environment" . }}
        product: {{ .Values.product }}
        helm.sh/chart: {{ include "rails.chart" . }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "lo-tools"
        vault.hashicorp.com/namespace: "admin"
        vault.hashicorp.com/log-level: "trace"
        vault.hashicorp.com/agent-inject-secret-export-envs.sh: "secret/lo-tools"
        vault.hashicorp.com/agent-inject-template-export-envs.sh: |
          {{`{{ with secret "secret/lo-tools" -}}
          export DATABASE_URL={{ .Data.data.db_connection_url }}
          export EXAMPLE_API_KEY={{ .Data.data.example_api_key }}
          {{ end -}} `}}
        vault.hashicorp.com/agent-inject-secret-database.yaml: "secret/lo-tools"
        vault.hashicorp.com/agent-inject-template-database.yaml: |
          {{`staging:
          {{- with secret "secret/lo-tools" }}
            url: {{ .Data.data.db_connection_url }}
          {{ end -}}`}}
        vault.hashicorp.com/agent-inject-secret-all-secrets.txt: "secret/lo-tools"
        vault.hashicorp.com/agent-inject-template-all-secrets.txt: |
          {{`{{ with secret "secret/lo-tools" -}}
          {{ range $k, $v := .Data.data -}}
          {{ $k }}: {{ $v }}
          {{ end -}}
          {{ end -}}`}}
    spec:
      serviceAccountName: {{ .Values.product }}
      containers:
      - name: {{ include "rails.name" . }}-webserver
        image: {{ .Values.image.repository }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["sh","-c","{{ .Values.webserver.command }}"]
        {{- if $.Values.webserver.lifecycle.enabled }}
        lifecycle:
{{ toYaml $.Values.webserver.lifecycle.hooks | indent 10 }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.webserver.port }}
        env:
        - name: SENTRY_RELEASE
          value: "{{ include "rails.product" . }}-{{ include "rails.version" . }}"
        - name: PORT
          value: {{ .Values.webserver.port | quote }}
        {{ if .Values.datadog.enabled }}
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_VERSION
          value: "{{ include "rails.version" . }}"
        {{- end }}
        {{- if .Values.custom_configs.enabled }}
        envFrom:
        - secretRef:
           name: {{ .Values.product }}-envvars
        volumeMounts:
          {{- range $index, $config := .Values.custom_configs.files}}
          - name: {{ $.Values.product }}{{ $config | replace "/" "-" | replace "." "-" | replace "_" "-"}}-vol
            mountPath: {{ $config }}
            subPath: {{ base $config }}
            readOnly: true
          {{- end }}
        {{- end }}
        {{- if .Values.webserver.startupProbe.enabled }}
        startupProbe:
          httpGet:
            path: {{ .Values.webserver.startupProbe.path }}
            port: {{ .Values.webserver.startupProbe.port }}
          initialDelaySeconds: {{ .Values.webserver.startupProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.webserver.startupProbe.timeoutSeconds }}
          periodSeconds: {{ .Values.webserver.startupProbe.periodSeconds }}
          successThreshold: {{ .Values.webserver.startupProbe.successThreshold }}
          failureThreshold: {{ .Values.webserver.startupProbe.failureThreshold }}
        {{- end }}
        {{- if .Values.webserver.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: {{ .Values.webserver.readinessProbe.path }}
            port: {{ .Values.webserver.readinessProbe.port }}
          initialDelaySeconds: {{ .Values.webserver.readinessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.webserver.readinessProbe.timeoutSeconds }}
          periodSeconds: {{ .Values.webserver.readinessProbe.periodSeconds }}
          successThreshold: {{ .Values.webserver.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.webserver.readinessProbe.failureThreshold }}
        {{- end }}
        {{- if .Values.webserver.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: {{ .Values.webserver.livenessProbe.path }}
            port: {{ .Values.webserver.livenessProbe.port }}
          initialDelaySeconds: {{ .Values.webserver.livenessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.webserver.livenessProbe.timeoutSeconds }}
          periodSeconds: {{ .Values.webserver.livenessProbe.periodSeconds }}
          successThreshold: {{ .Values.webserver.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.webserver.livenessProbe.failureThreshold }}
        {{- end }}
        resources:
{{ toYaml .Values.webserver.resources | indent 10 }}
      dnsPolicy: {{ default "ClusterFirst" .Values.dnsPolicy }}
      terminationGracePeriodSeconds: {{ default "30" $.Values.webserver.terminationGracePeriodSeconds }}
      securityContext:
        fsGroup: {{ .Values.securityContextID }}
        runAsUser: {{ .Values.securityContextID }}
      {{- if .Values.image_private_registry.enabled }}
      imagePullSecrets:
       - name: {{ .Values.image_private_registry.secret }}
      {{- end }}
      {{ if .Values.custom_configs.enabled -}}
      volumes:
        {{- range $index, $config := .Values.custom_configs.files}}
        - name: {{ $.Values.product }}{{ $config | replace "/" "-" | replace "." "-" | replace "_" "-"}}-vol
          secret:
            secretName: {{ $.Values.product }}{{ $config | replace "/" "-" | replace "." "-" | replace "_" "-"}}
        {{- end }}
      {{- end }}
{{- end }}
