
{{- if $.Values.worker.enabled -}}
  {{- range $index, $command := $.Values.worker.command }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rails.name" $ }}-worker-{{ $index }}
  labels:
    app: {{ include "rails.name" $ }}-worker
    app.kubernetes.io/name: {{ include "rails.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/version: {{ include "rails.version" $ }}
    environment: {{ include "rails.environment" $ }}
    product: {{ $.Values.product }}
    helm.sh/chart: {{ include "rails.chart" $ }}
spec:
  replicas: {{ $.Values.worker.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "rails.name" $ }}-worker
      app.kubernetes.io/name: {{ include "rails.name" $ }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
      environment: {{ include "rails.environment" $ }}
      product: {{ $.Values.product }}
  minReadySeconds: {{ $.Values.replica.minReadySeconds }}
  progressDeadlineSeconds: {{ $.Values.replica.progressDeadlineSeconds }}
  revisionHistoryLimit: {{ $.Values.replica.revisionHistoryLimit }}
  strategy:
    type: {{ $.Values.replica.strategy }}
  template:
    metadata:
      labels:
        app: {{ include "rails.name" $ }}-worker
        app.kubernetes.io/name: {{ include "rails.name" $ }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
        app.kubernetes.io/managed-by: {{ $.Release.Service }}
        app.kubernetes.io/version: {{ include "rails.version" $ }}
        environment: {{ include "rails.environment" $ }}
        product: {{ $.Values.product }}
        helm.sh/chart: {{ include "rails.chart" $ }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
      {{- $rails_name := include "rails.name" $ -}}
      {{- $rails_product := include "rails.product" $ -}}
      {{- $rails_version := include "rails.version" $ }}
      - name: {{ $rails_name }}-worker
        image: {{ $.Values.image.repository }}
        imagePullPolicy: {{ $.Values.image.pullPolicy }}
        command: ["sh","-c","{{ $command }}"]
        {{- if $.Values.worker.lifecycle.enabled }}
        lifecycle:
{{ toYaml $.Values.worker.lifecycle.hooks | indent 10 }}
        {{- end }}
        env:
        - name: SENTRY_RELEASE
          value: "{{ $rails_product }}-{{ $rails_version }}"
        {{- if $.Values.datadog.enabled }}
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        {{- end }}
        {{- if $.Values.custom_configs.enabled }}
        envFrom:
        - secretRef:
           name: {{ $.Values.product }}-envvars
        volumeMounts:
          {{- range $index, $config := $.Values.custom_configs.files}}
          - name: {{ $.Values.product }}{{ $config | replace "/" "-" | replace "." "-" | replace "_" "-"}}-vol
            mountPath: {{ $config }}
            subPath: {{ base $config }}
            readOnly: true
          {{- end }}
        {{- end }}
        {{- if $.Values.worker.startupProbe.enabled }}
        startupProbe:
          exec:
            command: {{ $.Values.worker.startupProbe.command }}
          initialDelaySeconds: {{ default "0" $.Values.worker.startupProbe.initialDelaySeconds }}
          timeoutSeconds: {{ $.Values.worker.startupProbe.timeoutSeconds }}
          periodSeconds: {{ $.Values.worker.startupProbe.periodSeconds }}
          successThreshold: {{ $.Values.worker.startupProbe.successThreshold }}
          failureThreshold: {{ $.Values.worker.startupProbe.failureThreshold }}
        {{- end }}
        {{- if $.Values.worker.readinessProbe.enabled }}
        readinessProbe:
          exec:
            command: {{ $.Values.worker.readinessProbe.command }}
          initialDelaySeconds: {{ $.Values.worker.readinessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ $.Values.worker.readinessProbe.timeoutSeconds }}
          periodSeconds: {{ $.Values.worker.readinessProbe.periodSeconds }}
          successThreshold: {{ $.Values.worker.readinessProbe.successThreshold }}
          failureThreshold: {{ $.Values.worker.readinessProbe.failureThreshold }}
        {{- end }}
        {{- if $.Values.worker.livenessProbe.enabled }}
        livenessProbe:
          exec:
            command: {{ $.Values.worker.livenessProbe.command }}
          initialDelaySeconds: {{ $.Values.worker.livenessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ $.Values.worker.livenessProbe.timeoutSeconds }}
          periodSeconds: {{ $.Values.worker.livenessProbe.periodSeconds }}
          successThreshold: {{ $.Values.worker.livenessProbe.successThreshold }}
          failureThreshold: {{ $.Values.worker.livenessProbe.failureThreshold }}
        {{- end }}
        resources:
{{ toYaml $.Values.worker.resources | indent 10 }}
      {{- if $.Values.image_private_registry.enabled }}
      imagePullSecrets:
      - name: {{ $.Values.image_private_registry.secret }}
      {{- end }}
      dnsPolicy: {{ default "ClusterFirst" $.Values.dnsPolicy }}
      terminationGracePeriodSeconds: {{ default "30" $.Values.worker.terminationGracePeriodSeconds }}
      securityContext:
        fsGroup: {{ $.Values.securityContextID }}
        runAsUser: {{ $.Values.securityContextID }}
      {{ if $.Values.custom_configs.enabled -}}
      volumes:
        {{- range $index, $config := $.Values.custom_configs.files}}
        - name: {{ $.Values.product }}{{ $config | replace "/" "-" | replace "." "-" | replace "_" "-"}}-vol
          secret:
            secretName: {{ $.Values.product }}{{ $config | replace "/" "-" | replace "." "-" | replace "_" "-"}}
        {{- end }}
        {{- end }}

  {{- end }}

{{- end }}
