{{- if .Values.worker.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rails.name" . }}-worker
  labels:
    app: {{ include "rails.name" . }}-worker
    app.kubernetes.io/name: {{ include "rails.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ include "rails.version" . }}
    environment: {{ include "rails.environment" . }}
    product: {{ .Values.product }}
    helm.sh/chart: {{ include "rails.chart" . }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "rails.name" . }}-worker
      app.kubernetes.io/name: {{ include "rails.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      environment: {{ include "rails.environment" . }}
      product: {{ .Values.product }}
  minReadySeconds: {{ .Values.replica.minReadySeconds }}
  progressDeadlineSeconds: {{ .Values.replica.progressDeadlineSeconds }}
  revisionHistoryLimit: {{ .Values.replica.revisionHistoryLimit }}
  strategy:
    type: {{ .Values.replica.strategy }}
  template:
    metadata:
      labels:
        app: {{ include "rails.name" . }}-worker
        app.kubernetes.io/name: {{ include "rails.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/version: {{ include "rails.version" . }}
        environment: {{ include "rails.environment" . }}
        product: {{ .Values.product }}
        helm.sh/chart: {{ include "rails.chart" . }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
      {{- $rails_name := include "rails.name" . -}}
      {{- $rails_product := include "rails.product" . -}}
      {{- $rails_version := include "rails.version" . -}}
      {{- range $index, $command := .Values.worker.command }}
      - name: {{ $rails_name }}-worker-{{ $index }}
        image: {{ $.Values.image.repository }}
        imagePullPolicy: {{ $.Values.image.pullPolicy }}
        command: ["sh","-c","{{ $command }}"]
        {{- if $.Values.worker.lifecycle.enabled }}
        lifecycle:
{{ toYaml $.Values.worker.lifecycle.hooks | indent 10 }}
        {{- end }}
        env:
        - name: SENTRY_RELEASE
          value: "{{ $rails_product }}-{{ $rails_version }}"
        {{- if $.Values.datadog.enabled }}
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        {{- end }}
        {{- if $.Values.custom_configs.enabled }}
        envFrom:
        - secretRef:
           name: {{ $.Values.product }}-envvars
        volumeMounts:
          {{- range $index, $config := $.Values.custom_configs.files}}
          - name: {{ $.Values.product }}{{ $config | replace "/" "-" | replace "." "-" | replace "_" "-"}}-vol
            mountPath: {{ $config }}
            subPath: {{ base $config }}
            readOnly: true
          {{- end }}
        {{- end }}
        {{- if $.Values.worker.readinessProbe.enabled }}
        readinessProbe:
          exec:
            command: {{ $.Values.worker.readinessProbe.command }}
          initialDelaySeconds: {{ default "0" $.Values.worker.readinessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ default "1" $.Values.worker.readinessProbe.timeoutSeconds }}
          periodSeconds: {{ default "10" $.Values.worker.readinessProbe.periodSeconds }}
          successThreshold: {{ default "1" $.Values.worker.readinessProbe.successThreshold }}
          failureThreshold: {{ default "3" $.Values.worker.readinessProbe.failureThreshold }}
        {{- end }}
        {{- if $.Values.worker.livenessProbe.enabled }}
        livenessProbe:
          exec:
            command: {{ $.Values.worker.livenessProbe.command }}
          initialDelaySeconds: {{ default "0" $.Values.worker.livenessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ default "1" $.Values.worker.livenessProbe.timeoutSeconds }}
          periodSeconds: {{ default "10" $.Values.worker.livenessProbe.periodSeconds }}
          successThreshold: {{ default "1" $.Values.worker.livenessProbe.successThreshold }}
          failureThreshold: {{ default "3" $.Values.worker.livenessProbe.failureThreshold }}
        {{- end }}
        resources:
{{ toYaml $.Values.worker.resources | indent 10 }}
      {{- end }}
      {{- if $.Values.image_private_registry.enabled }}
      imagePullSecrets:
      - name: {{ $.Values.image_private_registry.secret }}
      {{- end }}
      dnsPolicy: {{ default "Default" $.Values.dnsPolicy }}
      terminationGracePeriodSeconds: {{ default "30" $.Values.worker.terminationGracePeriodSeconds }}
      securityContext:
        fsGroup: {{ .Values.securityContextID }}
        runAsUser: {{ .Values.securityContextID }}
      {{ if $.Values.custom_configs.enabled -}}
      volumes:
        {{- range $index, $config := $.Values.custom_configs.files}}
        - name: {{ $.Values.product }}{{ $config | replace "/" "-" | replace "." "-" | replace "_" "-"}}-vol
          secret:           
            secretName: {{ $.Values.product }}{{ $config | replace "/" "-" | replace "." "-" | replace "_" "-"}}
        {{- end }}
        {{- end }}

{{- end }}