{{ if (and .Values.webserver.enabled .Values.webserver.autoscaling.enabled) -}}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "rails.name" . }}-webserver-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "rails.name" . }}-webserver
  minReplicas: {{ .Values.webserver.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.webserver.autoscaling.maxReplicas }}
  metrics:
  - type: {{ .Values.webserver.autoscaling.type }}
{{ toYaml .Values.webserver.autoscaling.metrics | indent 4 }}
{{- end }}
