{{ if (and .Values.worker.enabled .Values.worker.autoscaling.enabled) -}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "rails.name" . }}-worker-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "rails.name" . }}-worker
  minReplicas: {{ .Values.worker.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.worker.autoscaling.maxReplicas }}
  metrics:
  - type: {{ .Values.worker.autoscaling.type }}
{{ toYaml .Values.worker.autoscaling.metrics | indent 4 }}
{{- end }}
