{{ if (and .Values.webserver.enabled .Values.ingress.enabled) }}
{{- range $index, $list := .Values.ingress.list }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "rails.name" $ }}-ingress-{{ .type }}-{{ $index }}
  annotations:
    kubernetes.io/ingress.class: {{ .type | quote  }}
    {{- range $key, $value := .annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- if or .deny_locations .server_snippet }}
    nginx.ingress.kubernetes.io/server-snippet: |
    {{- if .deny_locations }}
    {{- range .deny_locations }}
      location {{ . }} { deny all; }
    {{- end }}
    {{- end }}
    {{- if .server_snippet }}
{{ toYaml .server_snippet | trimAll "|" | indent 4 }}
    {{- end }}
    {{- end }}
  labels:
    app: {{ include "rails.name" $ }}-ingress
    app.kubernetes.io/name: {{ include "rails.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/version: {{ include "rails.version" $ }}
    environment: {{ include "rails.environment" $ }}
    product: {{ $.Values.product }}
    helm.sh/chart: {{ include "rails.chart" $ }}
spec:
  rules:
    - host: {{ .host }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "rails.name" $ }}
                port:
                  number: {{ $.Values.webserver.port }}
            path: {{ default "/" .path }}
            pathType: {{ default "Prefix" .pathType }}
{{- if .tls.enabled }}
  tls:
    - hosts:
        - {{ .host }}
      secretName: {{ .tls.secret }}
{{- end }}
{{ end }}
{{- end }}
