{{ if (and .Values.webserver.enabled .Values.ingress_public.enabled) }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "rails.name" . }}-ingress-public
  annotations:
  {{- range $key, $value := .Values.ingress_public.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  labels:
    app: {{ include "rails.name" . }}-ingres
    app.kubernetes.io/name: {{ include "rails.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ include "rails.version" . }}
    environment: {{ include "rails.environment" . }}
    product: {{ .Values.product }}
    helm.sh/chart: {{ include "rails.chart" . }}
spec:
  rules:
    - host: {{ .Values.ingress_public.host }}
      http:
        paths:
          - backend:
              serviceName: {{ include "rails.name" . }}
              servicePort: {{ .Values.webserver.port }}
{{- if .Values.ingress_public.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress_public.host }}
      secretName: {{ .Values.ingress_public.tls.secret }}
{{- end }}
{{- end }}
