{{ if .Values.migrations.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "rails.name" . }}-migrations
  labels:
    app: {{ include "rails.name" . }}-migrations
    app.kubernetes.io/name: {{ include "rails.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ include "rails.version" . }}
    environment: {{ include "rails.environment" . }}
    product: {{ .Values.product }}
    helm.sh/chart: {{ include "rails.chart" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    {{- range $key, $value := .Values.migrations.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: {{ include "rails.name" . }}-migrations
        app.kubernetes.io/name: {{ include "rails.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/version: {{ include "rails.version" . }}
        environment: {{ include "rails.environment" . }}
        product: {{ .Values.product }}
        helm.sh/chart: {{ include "rails.chart" . }}
    spec:
{{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.product }}
{{- end }}
      containers:
      {{- $rails_name := include "rails.name" . -}}
      {{- $rails_product := include "rails.product" . -}}
      {{- $rails_version := include "rails.version" . -}}
      {{- range $index, $command := .Values.migrations.commands }}
      - name: {{ $rails_name }}-migrations-{{ $index }}
        image: {{ $.Values.image.repository }}
        command: ["sh","-c","{{ $command }}"]
        {{ if $.Values.datadog.enabled }}
        env:
        - name: SENTRY_RELEASE
          value: "{{ $rails_product }}-{{ $rails_version }}"
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        {{- end }}
        {{ if $.Values.custom_configs.enabled -}}
        envFrom:
        - secretRef:
           name: {{ $.Values.product }}-envvars
        volumeMounts:
          {{- range $index, $config := $.Values.custom_configs.files}}
          - name: {{ $.Values.product | trunc 18 }}-migrations{{ $config | replace "/" "-" | replace "." "-" | replace "_" "-" | trunc 30 }}-vol
            mountPath: {{ $config }}
            subPath: {{ base $config }}
            readOnly: true
          {{- end }}
{{- if $.Values.vault.enabled }}
          - name: vault-token
            mountPath: /vault-k8s-init-dir
{{- end }}
        {{- end }}
      {{- end }}
      restartPolicy: Never
{{- if .Values.vault.enabled }}
      initContainers:
      - name: get-vault-token
        image: {{ .Values.vault.initImage }}
        command:
        - sh
        - /get_vault_token.sh
        envFrom:
        - secretRef:
           name: {{ .Values.product }}-envvars
        volumeMounts:
          - name: vault-token
            mountPath: /vault-k8s-init-dir
{{- end }}
      dnsPolicy: {{ default "ClusterFirst" .Values.dnsPolicy }}
      {{- if $.Values.image_private_registry.enabled }}
      imagePullSecrets:
       - name: {{ $.Values.image_private_registry.secret }}
      {{- end }}
      {{ if $.Values.custom_configs.enabled -}}
      volumes:
        {{- range $index, $config := $.Values.custom_configs.files}}
        - name: {{ $.Values.product | trunc 18 }}-migrations{{ $config | replace "/" "-" | replace "." "-" | replace "_" "-" | trunc 30 }}-vol
          secret:
            secretName: {{ $.Values.product }}-migrations{{ $config | replace "/" "-" | replace "." "-" | replace "_" "-"}}
        {{- end }}
      {{- end }}
{{- if .Values.vault.enabled }}
        - name: vault-token
          emptyDir: {}
{{- end }}
{{- end }}
