global:
  # Default values for application charts.
  application:
    # Product name (e.g online-bind)
    product: ""
    # Application environment that it is running in (staging/production)
    environment: ""
    # Application version ("release-2021-03-04-01")
    version: ""

    # Config files to be mounted to application containers
    configFiles: {}
    # Path to config files on local disk. Note this value is for documentation purposes. Real default is inside of _config-files.yaml
    configFilePathTemplate: "configs/{{ $.Values.global.environment }}"

  # Global configuration for application monitoring tools
  applicationMonitoring:
    # Enable datadog monitoring and include additional labels to deployment
    datadog: false
    # Provision environment variables for Sentry exception tracking
    sentry: false

# Application component that is deployed
component: ""
