global:
  application:
    product: myproduct
    environment: test
    version: 3.1.2

  applicationImage:
    repository: "bitnami/ruby"

  mesh:
    enabled: false

command: ruby -e "puts 'test'"

serviceAccount:
  name: default
