apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "application-helpers.fullname" . }}
  labels:
    {{- include "application-helpers.labels" . | nindent 4 }}
    {{- if .Values.global.applicationMonitoring.datadog }}
    {{- include "application-helpers.monitoring.datadog.labels" . | nindent 4 }}
    {{- end }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    {{- with .Values.job.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  backoffLimit: 0
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
        {{- with .Values.job.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.global.applicationMonitoring.datadog }}
        ad.datadoghq.com/{{ include "application-helpers.fullname" . }}.logs: '[{"source": "{{ .Values.job.logs.source }}"}]'
        {{- end }}
      labels:
        {{- include "application-helpers.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ .Values.component }}
        {{- if .Values.global.applicationMonitoring.datadog }}
        {{- include "application-helpers.monitoring.datadog.labels" . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.global.applicationImage.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.global.applicationImage.pullSecret }}
      {{- end }}
      serviceAccountName: {{ include "application-helpers.serviceAccountName" . }}
      dnsPolicy: {{ .Values.job.dnsPolicy }}
      dnsConfig:
      {{- if .Values.job.dnsConfig }}
        {{- toYaml .Values.job.dnsConfig | nindent 8 }}
      {{- else }}
        {{- toYaml .Values.defaults.dnsConfig | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.job.terminationGracePeriodSeconds }}
      restartPolicy: Never
      securityContext:
        {{- toYaml .Values.job.securityContext | nindent 8 }}
      containers:
        - name: {{ include "application-helpers.fullname" . }}
          image: {{ include "application-helpers.docker-image" . | quote }}
          {{- if .Values.command }}
          command:
            - "sh"
            - "-c"
            {{- if .Values.global.mesh.enabled }}
            - |
              until wget --quiet --spider -o /dev/null http://localhost:15020/healthz/ready; do echo 'Waiting for Istio...'; sleep 1; done;
              echo 'Istio ready. Running the command...';
              {{ .Values.command }};
              x=$(echo $?);
              wget quiet --post-data="Please exit" -o /dev/null http://localhost:15020/quitquitquit && exit $x
            {{- else }}
            - {{ .Values.command | quote }}
            {{- end }}
          {{- end }}
          imagePullPolicy: {{ .Values.global.applicationImage.pullPolicy }}
          {{- if or .Values.global.applicationMonitoring.datadog .Values.global.applicationMonitoring.sentry .Values.job.env }}
          env:
          {{- if .Values.global.applicationMonitoring.datadog }}
          {{- include "application-helpers.monitoring.datadog.env" . | nindent 12 }}
          {{- end }}
          {{- if .Values.global.applicationMonitoring.sentry }}
          {{- include "application-helpers.monitoring.sentry.env" . | nindent 12 }}
          {{- end }}
          {{- with .Values.job.env }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if or .Values.global.application.environmentVariables .Values.job.envFrom }}
          envFrom:
          {{- with .Values.global.application.environmentVariables }}
            - secretRef:
                name: {{ include "application-helpers.configs.environment-variables.volume-name" $ }}
          {{- end }}
          {{- with .Values.job.envFrom }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
{{- /*          {{- if or .Values.global.application.configFiles .Values.job.volumeMounts }}*/}}
          volumeMounts:
            {{- /* Mount service account token to hardcoded path for backward compatibility with settings_reader-vault_resolver <= 0.4.9*/}}
            {{- /* should be removed once we make settings_reader-vault_resolver read token from default location or support custom token location*/}}
            - name: dynamic-sa-token
              mountPath: /var/run/secrets/tokens
              readOnly: true
          {{- with .Values.global.application.configFiles }}
          {{- range $name, $path := . }}
            - name: {{ include "application-helpers.configs.files-migration.volume-name" $ }}
              mountPath: {{ $path | quote }}
              subPath: {{ $name | quote }}
              readOnly: true
          {{- end }}
          {{- end }}
          {{- with .Values.job.volumeMounts }}
          {{- toYaml . | nindent 12 }}
          {{- end }}
{{- /*          {{- end }}*/}}
          resources:
            {{- toYaml .Values.job.resources | nindent 12 }}
{{- /*      {{- if or .Values.job.volumes .Values.global.application.configFiles }}*/}}
      volumes:
          {{- /* Mount service account token to hardcoded path for backward compatibility with settings_reader-vault_resolver <= 0.4.9*/}}
          {{- /* should be removed once we make settings_reader-vault_resolver read token from default location or support custom token location*/}}
        - name: dynamic-sa-token
          projected:
            sources:
              - serviceAccountToken:
                  path: dynamic-sa-token
                  expirationSeconds: 600
      {{- with .Values.global.application.configFiles }}
        - name: {{ include "application-helpers.configs.files-migration.volume-name" $ }}
          secret:
            secretName: {{ include "application-helpers.configs.files-migration.volume-name" $ }}
      {{- end }}
      {{- with .Values.job.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- /*      {{- end }}*/}}
      {{- with .Values.job.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.job.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.job.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.job.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
