{{- if .Values.global.mesh.enabled }}
{{/* Root virtual services that configure routing inside of the mesh */}}
{{- range $_, $ingress := .Values.ingress }}
{{- if ne $ingress.host "example.matic.com" }}
{{- if or (eq $ingress.gateway "internal") (eq $ingress.gateway "external") }}
{{- $host := required "Ingress host must be specified" $ingress.host  }}
{{- $hosts := append ($ingress.additional_hosts | default $.Values.defaults.ingress.additional_hosts) $ingress.host }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $ingress.gateway }}
  namespace: istio-ingress
spec:
  dnsNames:
    {{- range $host := $hosts }}
    - {{ $host | quote }}
    {{- end }}
  issuerRef:
    name: cert-manager-webhook-dnsimple-production
    kind: ClusterIssuer
  secretName: {{ $host | replace "." "-" }}-tls
{{- end }}
{{- end }}
{{- end }}
{{- end }}