{{- if .Values.global.mesh.enabled }}
{{- range $_, $ingress := .Values.ingress }}
{{- if ne $ingress.host "example.matic.com" }}
{{- if or (eq $ingress.gateway "internal") (eq $ingress.gateway "external") }}
{{- $host := required "Ingress host must be specified" $ingress.host  }}
{{- $hosts := append ($ingress.additional_hosts | default $.Values.defaults.ingress.additional_hosts) $ingress.host }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $host | replace "." "-" }}
  namespace: istio-ingress
  labels:
    app.kubernetes.io/part-of: {{ $.Values.global.application.product }}
    app.kubernetes.io/version: {{ (required "$.Values.global.application.version is required for applicaiton deployment" $.Values.global.application.version) | quote }}
spec:
  dnsNames:
    {{- range $host := $hosts }}
    - {{ $host | quote }}
    {{- end }}
  issuerRef:
    name: cert-manager-webhook-dnsimple-production
    kind: ClusterIssuer
  secretName: {{ $host | replace "." "-" }}-tls
{{- end }}
{{- end }}
{{- end }}
{{- end }}