{{- if .Values.egress.enabled }}
{{- range $_, $destination := .Values.destinations }}
---
apiVersion: networking.istio.io/v1
kind: Sidecar
metadata:
  name: {{ include "application-mesh.component-fullname" (merge (dict "component" $destination.component) $) }}
spec:
  workloadSelector:
    labels:
      app.kubernetes.io/instance: {{ include "application-mesh.component-fullname" (merge (dict "component" $destination.component) $) }}
  outboundTrafficPolicy:
    mode: REGISTRY_ONLY
  egress:
  - hosts:
    - istio-egress/*
    - istio-system/*
{{- range $_, $egress := $.Values.egress.allowlist }}
{{- range $host := compact (append ($egress.hosts | default list) ($egress.host)) }}
    - "./{{ $host }}"
{{- end }}
{{- end }}
{{- end }}
{{- end }}
