{{- if .Values.global.mesh.enabled }}
{{- if .Values.max_request_bytes }}
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: {{ include "application-helpers.name" $ }}
spec:
  workloadSelector:
    labels:
      app.kubernetes.io/name: {{ .Values.global.application.product }}
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.buffer
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.http.buffer.v3.Buffer
          max_request_bytes: {{ .Values.max_request_bytes | int }}
{{- end }}
{{- end }}
