{{- if .Values.global.mesh.enabled }}
{{- range $_, $destination := .Values.destinations }}
{{- if ne (dig "settings" "max_request_bytes" "1048576" $destination) "1048576" }}
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: {{ include "application-helpers.name" $ }}-{{ $destination.component }}-request-size
  labels:
    app.kubernetes.io/part-of: {{ $.Values.global.application.product }}
    app.kubernetes.io/version: {{ (required "$.Values.global.application.version is required for applicaiton deployment" $.Values.global.application.version) | quote }}
spec:
  workloadSelector:
    labels:
      app.kubernetes.io/instance: {{ include "application-helpers.name" $ }}-{{ $destination.component }}
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
    patch:
      operation: INSERT_BEFORE
      value:
        name: envoy.filters.http.buffer
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.http.buffer.v3.Buffer
          max_request_bytes: {{ $destination.settings.max_request_bytes | int }}
{{- end }}
{{- end }}
{{- end }}
