{{- if .Values.global.mesh.enabled }}
{{- range $_, $egress := .Values.egress }}
{{- if ne $egress.name "example-service" }}
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: {{ $egress.full_name | default (printf "%s-%s" (include "application-helpers.name" $) $egress.name) }}
spec:
  hosts:
    {{- $_ := required "Egress host or hosts list is required" ($egress.hosts | default $egress.host) }}
    {{- range $host := compact (append ($egress.hosts | default list) ($egress.host)) }}
    - {{ $host }}
    {{- end }}
  ports:
    - name: {{ $egress.type }}
      number: {{ required "Egress port is required for non standard type" ($egress.port | default (get $.Values.defaults.egress.port $egress.type)) }}
      {{- if hasKey $.Values.defaults.egress.protocol $egress.type }}
      protocol: {{ get $.Values.defaults.egress.protocol $egress.type }}
      {{- else }}
      protocol: TCP
      {{- end }}
  location: MESH_EXTERNAL
  resolution: DNS
{{- end }}
{{- end }}
{{- end }}