{{- if .Values.enabled }}
{{- range $_, $destination := .Values.destinations }}
{{ $service_host := include "application-mesh.service-host" (merge (dict "component" $destination.component) $) }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "application-helpers.name" $ }}-{{ $destination.component }}
spec:
  hosts:
    - {{ $service_host }}
  gateways:
    - mesh
  http:
    - route:
        - destination:
            host: {{ $service_host }}
            subset: default
{{- end }}
{{- end }}
