{{- if .Values.enabled }}
{{/* Root virtual services that configure routing inside of the mesh */}}
{{- range $_, $destination := .Values.destinations }}
{{ $service_host := include "application-mesh.service-host" (merge (dict "component" $destination.component) $) }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "application-helpers.name" $ }}-{{ $destination.component }}
spec:
  hosts:
    - {{ $service_host }}
  gateways:
    - mesh
  http:
    - route:
        - destination:
            host: {{ $service_host }}
            subset: default
{{- end }}
{{- end }}
{{/* Virtual Services for pre-existing gateway (wildcard domain). Required to populate ExternalDNS and configure routing */}}
{{- range $_, $ingress := .Values.ingress }}
{{ $service_host := include "application-mesh.service-host" (merge (dict "component" $ingress.destination) $) }}
{{- $host := required "Ingress host must be specified" $ingress.host  }}
{{- $hosts := append ($ingress.additional_hosts | default $.Values.defaults.ingress.additional_hosts) $ingress.host }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "application-helpers.name" $ }}-{{ printf "%x" (atoi (adler32sum $host)) }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ $hosts | join ", " | quote }}
spec:
  hosts:
    {{- range $host := $hosts }}
    - {{ $host }}
    {{- end }}
  gateways:
    - istio-ingress/{{ required "Ingress gateway must be specified" $ingress.gateway}}
  http:
    {{- $deny_locations := $ingress.deny_locations | default $.Values.defaults.ingress.deny_locations }}
    {{- $allow_locations := $ingress.allow_locations | default $.Values.defaults.ingress.allow_locations }}
    {{- if gt (len $deny_locations) 0 }}
    {{- /* Has Deny locations specified */}}
    - route:
        name: deny-ingress-spec
        match:
          {{- range $path := $deny_locations }}
          - uri:
              prefix: {{ $path }}
          {{- end }}
        directResponse:
          status: 403
          body:
            string: Access Denied
    {{- end }}
    {{- if gt (len $allow_locations) 0 }}
    {{- /* Has Allow locations specified */}}
    - route:
        name: allow-ingress-spec
        match:
          {{- range $path := $allow_locations }}
          - uri:
              prefix: {{ $path }}
          {{- end }}
        destination:
          host: {{ $service_host }}
          subset: default
    - route:
        name: deny-everything-except-allowed
        directResponse:
          status: 403
          body:
            string: Access Denied
    {{ else }}
    {{- /* Route everything to service */}}
    - route:
        name: allow-all-locations
        destination:
          host: {{ $service_host }}
          subset: default
    {{- end }}
{{- end }}
