{{- if .Values.global.mesh.enabled }}
{{/* Root virtual services that configure routing inside of the mesh */}}
{{- range $_, $destination := .Values.destinations }}
{{ $service_host := include "application-mesh.service-host" (merge (dict "component" $destination.component) $) }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "application-helpers.name" $ }}-{{ $destination.component }}
  labels:
    app.kubernetes.io/part-of: {{ $.Values.global.application.product }}
    app.kubernetes.io/version: {{ (required "$.Values.global.application.version is required for applicaiton deployment" $.Values.global.application.version) | quote }}
spec:
  hosts:
    - {{ $service_host | quote }}
  gateways:
    - mesh
  http:
    - name: allow-all-locations
      route:
        - destination:
            host: {{ $service_host | quote }}
            subset: all-versions
          {{- include "application-mesh.proxy-tracing-headers" $ | nindent 10 }}
{{- end }}
{{- end }}
