{{- if .Values.ssl_certificate.enabled -}}
{{- range .Values.ssl_certificate.domains }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-tls
type: tls
data:
  tls.key: {{ .private_key }}
  tls.crt: {{ .certificate }}
{{- end }}
{{- end -}}

{{- if .Values.docker_hub_secrets.enabled -}}
{{- range .Values.docker_hub_secrets.logins }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-hub-login
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .dockerconfigjson }}
{{- end }}
{{- end -}}

{{- if .Values.custom.enabled -}}
{{- range .Values.custom.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
type: Opaque
data:
  key: {{ .value }}
{{- end }}
{{- end -}}