# Default values for rails.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

product: myproduct
environment: staging

image:
  repository: bitnami/ruby-example:0.0.1
  pullPolicy: IfNotPresent

image_private_registry:
  enabled: false
  secret: docker-login

custom_configs:
  enabled: false
  files:
  - /app/settings.yml
  - /app/some_config.yml

migrations:
  enabled: false
  commands:
  - "bundle exec rake db:migrate"

ingress:
  enabled: false
  host: myhost.local
  annotations: {}
  tls:
    enabled: false
    secret: myhost.local-tls

webserver:
  enabled: true
  command: "bundle exec puma"
  replicaCount: 1
  port: 3000
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 100m
  readinessProbe:
    path: /welcome/index
    port: 3000
    initialDelaySeconds: 10
    timeoutSeconds: 1
    periodSeconds: 20
  autoscaling:
    enabled: true
    minReplicas: 4
    maxReplicas: 12
    type: External
    metrics:
      external:
        metric:
          name: queue_messages_ready
          selector:
            queue: worker_tasks
        target:
          type: AverageValue
          averageValue: 30
  lifecycle:
    enabled: false

worker:
  enabled: false
  command:
  - "bundle exec sidekiq -q default -c 20"
  replicaCount: 1
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 128Mi
      cpu: 100m
  autoscaling:
    enabled: false
  lifecycle:
    enabled: false

replica:
  minReadySeconds: 1  # minimum number of seconds before Kubernetes starts considering the Pods healthy
  progressDeadlineSeconds: 120  # how much the Deployment has to wait before it deduces that it cannot progress due to a failure to run a Pod
  revisionHistoryLimit: 5  # number of ReplicaSet we can rollback
  strategy: RollingUpdate

service:
  type: ClusterIP

securityContextID: 100

datadog:
  enabled: false
