# Default values for rails.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

product: myproduct
environment: staging

image:
  repository: bitnami/ruby-example:0.0.1
  pullPolicy: IfNotPresent

image_private_registry:
  enabled: false
  secret: docker-login

custom_configs:
  enabled: false
  files:
  - /app/settings.yml
  - /app/some_config.yml

migrations:
  enabled: false
  commands:
  - "bundle exec rake db:migrate"

ingress:
  enabled: false
  list:
    - host: myhost1.local
      type: public
      annotations: {}
      server_snippet: |
        location /foldername-a {
          proxy_http_version 1.1;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
        location /foldername-b {
          proxy_set_header X-Forwarded-Host $http_host;
        }
      deny_locations:
        - /admin
        - /internal_api
        - /etc
      tls:
        enabled: false
        secret: myhost1.local-tls
    - host: myhost2.local
      type: private
      annotations: {}
      tls:
        enabled: false
        secret: myhost2.local-tls
webserver:
  enabled: true
  command: "bundle exec puma"
  replicaCount: 1
  port: 3000
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 100m
  startupProbe:
    enabled: false
    path: /welcome/index
    port: 3000
    initialDelaySeconds: 5
    timeoutSeconds: 5
    periodSeconds: 15
    successThreshold: 1
    failureThreshold: 20
  readinessProbe:
    enabled: false
    path: /welcome/index
    port: 3000
    initialDelaySeconds: 10
    timeoutSeconds: 10
    periodSeconds: 30
    successThreshold: 1
    failureThreshold: 10
  livenessProbe:
    enabled: false
    path: /welcome/index
    port: 3000
    initialDelaySeconds: 20
    timeoutSeconds: 20
    periodSeconds: 60
    successThreshold: 1
    failureThreshold: 10
  autoscaling:
    enabled: false
  lifecycle:
    enabled: false

workers:
  - name: default
    enabled: false
    command:
    - "bundle exec sidekiq -q default -c 20"
    replicaCount: 1
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 128Mi
        cpu: 100m
    autoscaling:
      enabled: false
    lifecycle:
      enabled: false
    startupProbe:
      enabled: false
      command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      timeoutSeconds: 5
      periodSeconds: 15
      successThreshold: 1
      failureThreshold: 20
    readinessProbe:
      enabled: false
      command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 10
      timeoutSeconds: 10
      periodSeconds: 30
      successThreshold: 1
      failureThreshold: 10
    livenessProbe:
      enabled: false
      command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 20
      timeoutSeconds: 20
      periodSeconds: 60
      successThreshold: 1
      failureThreshold: 10

replica:
  minReadySeconds: 1  # minimum number of seconds before Kubernetes starts considering the Pods healthy
  progressDeadlineSeconds: 120  # how much the Deployment has to wait before it deduces that it cannot progress due to a failure to run a Pod
  revisionHistoryLimit: 5  # number of ReplicaSet we can rollback
  strategy: RollingUpdate

service:
  type: ClusterIP
  annotations: {}

securityContextID: 100

datadog:
  enabled: false
