{{ if (and .Values.autoscaling.enabled) -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "application-component.fullname" . }}
  labels:
    {{- include "application-component.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "application-component.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  {{ if .Values.autoscaling.metrics -}}
  metrics:
  {{- range $index, $metric := .Values.autoscaling.metrics }}
    {{- if eq $metric.type "Datadog"}}
    - type: External
      external:
        metric:
          name: datadogmetric@{{ $.Values.environment  }}:{{ $metric.name }}
        target:
        {{- toYaml $metric.target | nindent 10 }}
    {{- else if eq $metric.type "External" }}
    - type: External
      external:
        {{- toYaml $metric.external | nindent 8 }}
    {{- else if eq $metric.type "Resource" }}
    - type: Resource
      resource:
        {{- toYaml $metric.resource | nindent 8 }}
    {{- end }}
  {{- end }}
  {{- end }}
  {{- with .Values.autoscaling.behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
