{{ if (and .Values.service.enabled .Values.ingress.enabled) }}
{{- range $index, $ingress := .Values.ingress.list }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "application-helpers.fullname" $ }}-ingress-{{ $ingress.type }}-{{ $index }}
  annotations:
    kubernetes.io/ingress.class: {{ required "Ingress type must be specified" $ingress.type | quote  }}
    {{- /* Get default annotations and merge them with one provided in config. Empty annotations discarded*/}}
    {{- $ingress_annotations := $ingress.annotations | default dict }}
    {{- $annotations := merge dict $ingress_annotations $.Values.defaults.ingress.annotations }}
    {{- range $key, $value := $annotations }}
    {{- /* Due to the bug https://github.com/helm/helm/issues/5274 need additional checks to allow clearing defaults */}}
    {{- if hasKey $ingress_annotations $key }}
      {{- if get $ingress_annotations $key }}
    {{ $key }}: {{ $value | quote }}
      {{- end }}
    {{- else if $value }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
    {{- /* Insert dns annotations related to host/additional host unless previously defined */}}
    {{- $additional_hosts := $ingress.additional_hosts | default $.Values.defaults.ingress.additional_hosts }}
    {{- if and ($additional_hosts) (not (hasKey $ingress_annotations "external-dns.alpha.kubernetes.io/hostname")) }}
    nginx.ingress.kubernetes.io/server-alias: {{ $additional_hosts | join ", " | quote }}
    {{- end }}
    {{- if not (hasKey $ingress_annotations "external-dns.alpha.kubernetes.io/hostname") }}
    external-dns.alpha.kubernetes.io/hostname: {{ append $additional_hosts $ingress.host | join ", " | quote }}
    {{- end }}
    {{- /* Insert custom server snippet and/or deny locations */}}
    {{- if or $ingress.deny_locations $ingress.server_snippet }}
    nginx.ingress.kubernetes.io/server-snippet: |
    {{- if $ingress.deny_locations }}
    {{- range $ingress.deny_locations }}
      location {{ . }} { deny all; }
    {{- end }}
    {{- end }}
    {{- if $ingress.server_snippet }}
{{ toYaml $ingress.server_snippet | trimAll "|" | indent 4 }}
    {{- end }}
    {{- end }}
    {{- if not (hasKey $ingress_annotations "nginx.ingress.kubernetes.io/configuration-snippet") }}
    {{- if $.Values.global.applicationMonitoring.datadog }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
        {{- /* Datadog: Tracing request inside nginx ingress https://docs.datadoghq.com/tracing/trace_collection/proxy_setup/?tab=nginx#nginx-ingress-controller-for-kubernetes */}}
        opentracing_tag "service.name" {{ printf "%s-%s" (include "application-helpers.name" $) "nginx" | quote}};
        {{- /* Datadog: Additional data for time request was queued https://docs.datadoghq.com/tracing/trace_collection/dd_libraries/ruby/#http-request-queuing */}}
        proxy_set_header X-Request-Start "t=${msec}";
    {{- end}}
    {{- end }}
  labels:
    {{- include "application-helpers.labels" $ | nindent 4 }}
spec:
  rules:
    - host: {{ required "Ingress host must be specified" $ingress.host }}
      http:
        paths:
          {{- range $path := ($ingress.allow_locations | default $.Values.defaults.ingress.allow_locations) }}
          - backend:
              service:
                name: {{ include "application-helpers.fullname" $ }}
                port:
                  number: {{ $.Values.deployment.port }}
            path: {{ $path }}
            pathType: Prefix
          {{- end }}
{{- if $ingress.tls }}
  tls:
    - hosts:
        - {{ $ingress.host }}
      secretName: {{ $ingress.tls }}
{{- end }}
{{- end }}
{{- end }}
