{{ if (and .Values.service.enabled .Values.ingress.enabled) }}
{{- range $index, $ingress := .Values.ingress.list }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "application-helpers.fullname" $ }}-ingress-{{ $ingress.type }}-{{ $index }}
  annotations:
    kubernetes.io/ingress.class: {{ required "Ingress type must be specified" $ingress.type | quote  }}
    {{- /* Get default annotations and merge them with one provided in config. Empty annotations discarded*/}}
    {{- $ingress_annotations := $ingress.annotations | default dict }}
    {{- $annotations := merge $ingress_annotations $.Values.ingress.default.annotations }}
    {{- range $key, $value := $annotations }}
    {{- if $value }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
    {{- /* Insert dns annotations related to host/additional host unless previously defined */}}
    {{- $additional_hosts := $ingress.additional_hosts | default $.Values.ingress.default.additional_hosts }}
    {{- if and ($additional_hosts) (not (hasKey $ingress_annotations "external-dns.alpha.kubernetes.io/hostname")) }}
    nginx.ingress.kubernetes.io/server-alias: {{ $additional_hosts | join ", " | quote }}
    {{- end }}
    {{- if not (hasKey $ingress_annotations "external-dns.alpha.kubernetes.io/hostname") }}
    external-dns.alpha.kubernetes.io/hostname: {{ append $additional_hosts $ingress.host | join ", " | quote }}
    {{- end }}
    {{- /* Insert custom server snippet and/or deny locations */}}
    {{- if or $ingress.deny_locations $ingress.server_snippet }}
    nginx.ingress.kubernetes.io/server-snippet: |
    {{- if $ingress.deny_locations }}
    {{- range $ingress.deny_locations }}
      location {{ . }} { deny all; }
    {{- end }}
    {{- end }}
    {{- if $ingress.server_snippet }}
{{ toYaml $ingress.server_snippet | trimAll "|" | indent 4 }}
    {{- end }}
    {{- end }}
  labels:
    {{- include "application-helpers.labels" $ | nindent 4 }}
spec:
  rules:
    - host: {{ required "Ingress host must be specified" $ingress.host }}
      http:
        paths:
          {{- range $path := ($ingress.allow_locations | default $.Values.ingress.default.allow_locations) }}
          - backend:
              service:
                name: {{ include "application-helpers.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
            path: {{ $path }}
            pathType: Prefix
          {{- end }}
{{- if $ingress.tls }}
  tls:
    - hosts:
        - {{ $ingress.host }}
      secretName: {{ $ingress.tls }}
{{- end }}
{{- end }}
{{- end }}
