{{- $availability := .Values.deployment.availability }}
{{- if not (eq $availability "irrelevant") }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "application-helpers.fullname" . }}
spec:
  maxUnavailable: 1
  {{- if eq $availability "critical" }}
  minAvailable: 2
  {{- end }}
  selector:
    matchLabels:
      {{- include "application-helpers.selectorLabels" . | nindent 6 }}
{{- end }}
{{- /* Availability checks */}}
{{- $deploymentMinPods := int (min .Values.deployment.replicas .Values.autoscaling.minReplicas) }}
{{- $placement := .Values.deployment.placement }}
{{- if eq $availability "critical" }}
    {{- if lt $deploymentMinPods 3 }}
        {{- fail "With availability critical - deployment and autoscaling should have at minimum 3 pods" }}
    {{- end }}
{{- else if or (eq $availability "high") (eq $availability "normal") }}
    {{- if lt $deploymentMinPods 2 }}
        {{- fail "With availability high and normal - deployment and autoscaling should have at minimum 2 pods" }}
    {{- end }}
{{- end }}