{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "application-component.fullname" . }}
  labels:
    {{- include "application-component.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $name, $port := .Values.service.ports }}
    - port: {{ $port }}
      targetPort: {{ $port }}
      protocol: TCP
      name: {{ $name }}
    {{- end }}
  selector:
    {{- include "application-component.selectorLabels" . | nindent 4 }}
  {{- end }}