{{- with .Values.global.application.environmentVariables }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "application-helpers.configs.environment-variables.volume-name" $ }}
  labels:
    {{- /*  Override component as it is not defined at place where we call this helper  */}}
    {{- include "application-helpers.labels" (merge (dict "Values" (dict "component" "configs")) $) | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  {{- $envvars := . }}
  {{- range $envvar, $value := $envvars }}
  {{ $envvar }}: {{ $value | quote | b64enc }}
{{- end }}
{{- end }}
