name: publish-charts

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          clean: true
          fetch-depth: '0'
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.1
      - name: Publish charts
        run: bash ops/scripts/publish.sh stable https://matic-insurance.github.io/helm-charts
