name: test-charts

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Lint charts
        id: lint
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: lint
          config: test/ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
        with:
          node_image: "kindest/node:v1.21.2"
        # Only build a kind cluster if there are chart changes to test.
        if: steps.lint.outputs.changed == 'true'

      - name: Install charts
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: install
          config: test/ct.yaml

  unit-test:
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Chart Dependencies
        uses: asdf-vm/actions/install@v1

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run Unit Tests
        run: go test ./...
