name: test-charts

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Lint charts
        id: lint
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: lint
          config: test/ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
        with:
          node_image: "kindest/node:v1.21.2"
        # Only build a kind cluster if there are chart changes to test.
        if: steps.lint.outputs.changed == 'true'

      - name: Install charts
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: install
          config: test/ct.yaml

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.2'
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Run Unit Tests
        run: go test ./...
