name: test-charts

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Lint charts
        id: lint
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: lint
          config: test/ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0
        with:
          node_image: "kindest/node:v1.17.5"
        # Only build a kind cluster if there are chart changes to test.
        if: steps.lint.outputs.changed == 'true'

      - name: Install charts
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: install
          config: test/ct.yaml
